## Importing necessary libraries

In [ ]:
import pandas as pd

## Loading the dataset and viewing first 5 rows

In [ ]:
# IMPORTANT: Update this path to your actual parquet file
parquet_file_path = "/content/drive/MyDrive/NYC dataset/cleaned_yellow_taxi_2025.parquet"

try:
    # Load the parquet file into a pandas DataFrame
    pandas_df = pd.read_parquet(parquet_file_path)

    print(f"Successfully loaded parquet file from {parquet_file_path} into a pandas DataFrame.")
    print("Shape of the DataFrame:", pandas_df.shape)
    print("First 5 rows of the DataFrame:")
    display(pandas_df.head())
except Exception as e:
    print(f"Error loading parquet file from {parquet_file_path}: {e}")
    print("Please ensure the path is correct and the file exists.")

Successfully loaded parquet file from /content/drive/MyDrive/NYC dataset/cleaned_yellow_taxi_2025.parquet into a pandas DataFrame.
Shape of the DataFrame: (18962717, 23)
First 5 rows of the DataFrame:

/usr/local/lib/python3.12/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.12/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,...,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee,LocationID,Borough,Zone,service_zone
0,2,2025-02-01 00:12:18,2025-02-01 00:32:33,3.0,3.12,1.0,246,79,1,19.799999,...,0.0,1.0,30.659374,2.5,0.0,0.75,246,Manhattan,West Chelsea/Hudson Yards,Yellow Zone
1,2,2025-02-01 00:40:04,2025-02-01 00:49:15,1.0,1.40,1.0,114,79,1,10.000000,...,0.0,1.0,18.900391,2.5,0.0,0.75,114,Manhattan,Greenwich Village South,Yellow Zone
2,1,2025-02-01 00:06:09,2025-02-01 00:11:51,1.0,0.40,1.0,211,144,1,6.500000,...,0.0,1.0,16.500000,2.5,0.0,0.75,211,Manhattan,SoHo,Yellow Zone
3,1,2025-02-01 00:15:13,2025-02-01 00:20:19,1.0,0.70,1.0,113,249,1,7.200000,...,0.0,1.0,18.200001,2.5,0.0,0.75,113,Manhattan,Greenwich Village North,Yellow Zone
4,2,2025-02-01 00:02:52,2025-02-01 00:20:25,1.0,4.19,1.0,113,263,1,19.799999,...,0.0,1.0,30.659374,2.5,0.0,0.75,113,Manhattan,Greenwich Village North,Yellow Zone

#### Checking the info of the dataset

In [ ]:
pandas_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18962717 entries, 0 to 18998027
Data columns (total 23 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               uint16
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float16
 4   trip_distance          float32
 5   RatecodeID             float16
 6   PULocationID           uint16
 7   DOLocationID           uint16
 8   payment_type           uint16
 9   fare_amount            float32
 10  extra                  float16
 11  mta_tax                float16
 12  tip_amount             float16
 13  tolls_amount           float16
 14  improvement_surcharge  float16
 15  total_amount           float32
 16  congestion_surcharge   float16
 17  Airport_fee            float16
 18  cbd_congestion_fee     float16
 19  LocationID             int64
 20  Borough                object
 21  Zone                   object
 22  service_zone           object
dtypes: datetime64[us](2), float16(10), float32(3), int64(1), object(3), uint16(4)
memory usage: 1.7+ GB

# Creating new features

#### fare_per_mile

In [ ]:
#fare per mile
pandas_df['fare_per_mile'] = pandas_df['fare_amount'] / pandas_df['trip_distance']

#### tip_percentage

In [ ]:
#tip pct(%)
pandas_df['tip_pct(%)'] = pandas_df['tip_amount'] / pandas_df['fare_amount']

#### trip_duration_in_minutes

In [ ]:
# Calculate trip duration in minutes
pandas_df['trip_duration_minutes'] = (pandas_df['tpep_dropoff_datetime'] - pandas_df['tpep_pickup_datetime']).dt.total_seconds() / 60

#### day_of_week, hour_of_the_day, month

In [ ]:
# Extract day of the week (Monday=0, Sunday=6)
pandas_df['pickup_day_of_week'] = pandas_df['tpep_pickup_datetime'].dt.dayofweek

# Extract hour of the day
pandas_df['pickup_hour'] = pandas_df['tpep_pickup_datetime'].dt.hour

# Extract month
pandas_df['pickup_month'] = pandas_df['tpep_pickup_datetime'].dt.month

#### is_weekend flag

In [ ]:
# Create a 'is_weekend' flag (Saturday=5, Sunday=6)
pandas_df['is_weekend'] = pandas_df['pickup_day_of_week'].isin([5, 6]).astype(int)

In [ ]:
print('First 5 rows with new features:')
display(pandas_df.head())
print('\nDataFrame info with new features:')
pandas_df.info()

First 5 rows with new features:

/usr/local/lib/python3.12/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.12/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,...,Borough,Zone,service_zone,fare_per_mile,tip_pct(%),trip_duration_minutes,pickup_day_of_week,pickup_hour,pickup_month,is_weekend
0,2,2025-02-01 00:12:18,2025-02-01 00:32:33,3.0,3.12,1.0,246,79,1,19.799999,...,Manhattan,West Chelsea/Hudson Yards,Yellow Zone,6.346154,0.258049,20.250000,5,0,2,1
1,2,2025-02-01 00:40:04,2025-02-01 00:49:15,1.0,1.40,1.0,114,79,1,10.000000,...,Manhattan,Greenwich Village South,Yellow Zone,7.142857,0.315039,9.183333,5,0,2,1
2,1,2025-02-01 00:06:09,2025-02-01 00:11:51,1.0,0.40,1.0,211,144,1,6.500000,...,Manhattan,SoHo,Yellow Zone,16.250000,0.153846,5.700000,5,0,2,1
3,1,2025-02-01 00:15:13,2025-02-01 00:20:19,1.0,0.70,1.0,113,249,1,7.200000,...,Manhattan,Greenwich Village North,Yellow Zone,10.285714,0.277778,5.100000,5,0,2,1
4,2,2025-02-01 00:02:52,2025-02-01 00:20:25,1.0,4.19,1.0,113,263,1,19.799999,...,Manhattan,Greenwich Village North,Yellow Zone,4.725537,0.258049,17.550000,5,0,2,1

DataFrame info with new features:
<class 'pandas.core.frame.DataFrame'>
Index: 18962717 entries, 0 to 18998027
Data columns (total 30 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               uint16
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float16
 4   trip_distance          float32
 5   RatecodeID             float16
 6   PULocationID           uint16
 7   DOLocationID           uint16
 8   payment_type           uint16
 9   fare_amount            float32
 10  extra                  float16
 11  mta_tax                float16
 12  tip_amount             float16
 13  tolls_amount           float16
 14  improvement_surcharge  float16
 15  total_amount           float32
 16  congestion_surcharge   float16
 17  Airport_fee            float16
 18  cbd_congestion_fee     float16
 19  LocationID             int64
 20  Borough                object
 21  Zone                   object
 22  service_zone           object
 23  fare_per_mile          float32
 24  tip_pct(%)             float32
 25  trip_duration_minutes  float64
 26  pickup_day_of_week     int32
 27  pickup_hour            int32
 28  pickup_month           int32
 29  is_weekend             int64
dtypes: datetime64[us](2), float16(10), float32(5), float64(1), int32(3), int64(2), object(3), uint16(4)
memory usage: 2.3+ GB
Warning: Total number of columns (30) exceeds max_columns (20) limiting to first (20) columns.

/usr/local/lib/python3.12/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

#### Converting this into parquet. We will perform data cleaning, EDA, hypothesis testing on this dataset.

In [ ]:
pandas_df.to_parquet('Yellow_taxi_2025.parquet')